### ISSUE TITLE
[Bug Report] Missing experimental package

### ISSUE THREAD

**Issue by awonak** [Allen-Synthesis/EuroPi#164]
# Bug Report

**Describe the bug**  
EuroPi v0.6.0 introduces `experimental` package and is imported with:

```
    from experimental.knobs import KnobBank
```

However since the `experimental` package isn't included in the pypi package, loading a script that depends on it will throw an error:

```
MicroPython v1.18 on 2022-01-17; Raspberry Pi Pico with RP2040

Type "help()" for more information.
>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 19, in <module>
  File "/lib/contrib/turing_machine.py", line 37, in <module>
ImportError: no module named 'experimental'
>>> 
```

**Comment by awonak** [comment]
For a quick fix, comment out lines [line 19](https://github.com/Allen-Synthesis/EuroPi/blob/main/software/contrib/menu.py#L19) and [line 39](https://github.com/Allen-Synthesis/EuroPi/blob/main/software/contrib/menu.py#L39) of your `main.py` copied from [menu.py](https://github.com/Allen-Synthesis/EuroPi/blob/main/software/contrib/menu.py)

**Comment by awonak** [comment]
I have deleted the tag `0.6.0` and [yanked](https://pypi.org/help/#yanked) the release from pypi.

**Comment by awonak** [comment]
Fixed in https://github.com/Allen-Synthesis/EuroPi/commit/b5f9c9f61f7f5d8dc8af27b4c8d98dc7641d5393
